### ISSUE TITLE
Finish Calendar on STR Dashboard

### ISSUE THREAD

**Issue by Ayden1456** [Ayden1456/ramv4#3]
#### Description
The calendar needs to have additional features that will help users track expiring leases etc.

#### Files
Start at the STR dashboard
This uses the calendar.io docs https://fullcalendar.io/docs/getting-started

#### Tasks
- [x] Put in the right calendar
- [x] Put in the toggle for week/month
- [x] Put in test events

**Comment by ricePak** [comment]
Issue resolved?

**Comment by Ayden1456** [comment]
Yes :)

**Comment by ricePak** [comment]
Time to close this issue!
> Yes :)
> 
> 
>
